spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: false
  web:
    resources:
      chain:
        compressed: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    aws:
      region:
        static: ap-northeast-2
server:
  port: 8000
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_DEMO
    encoding:
      charset: UTF-8
      enabled: true
      force: true
sentry:
  dsn:
  traces-sample-rate: 0
jwt:
  secret: JOONY.KIM!!demo-api%%jwt^^secret
  access-token-expiration-minutes: 5
  refresh-token-expiration-minutes: 30
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://database-1.cdomw0u4mc2w.ap-northeast-2.rds.amazonaws.com:3306/demo?useSSL=false&serverTimezone=UTC
    username: demo
    password: demo!%$@
    pool:
      max-size: 3
      min-idle: 2
      initial-size: 2
sentry:
  logging:
    enabled: false
environment:
  app:
    test: test
jwt:
  access-token-expiration-minutes: 1440
---
spring:
  config:
    activate:
      on-profile: sandbox
  r2dbc:
    url:
    username:
    password:
    pool:
      max-size: 5
      min-idle: 3
      initial-size: 3
sentry:
  environment: sandbox
jwt:
  access-token-expiration-minutes: 1440
---
spring:
  config:
    activate:
      on-profile: qa
  r2dbc:
    url:
    username:
    password:
    pool:
      max-size: 10
      min-idle: 5
      initial-size: 5
sentry:
  environment: qa
---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url:
    username:
    password:
    pool:
      max-size: 30
      min-idle: 10
      initial-size: 10
springdoc:
  api-docs:
    enabled: false
sentry:
  environment: prod
